# Generated by Django 3.2.13 on 2022-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryShipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippingName', models.CharField(blank=True, max_length=100)),
                ('zipCode', models.CharField(blank=True, max_length=100)),
                ('countryId', models.CharField(blank=True, max_length=20)),
                ('stateId', models.CharField(blank=True, max_length=20)),
                ('shippingType', models.CharField(blank=True, max_length=100)),
                ('shippingAddress', models.TextField(blank=True)),
                ('createDate', models.CharField(blank=True, max_length=100)),
                ('createTime', models.CharField(blank=True, max_length=100)),
                ('createdBy', models.IntegerField(default=0)),
                ('deliveryId', models.IntegerField(default=0)),
                ('updateDate', models.CharField(blank=True, max_length=100)),
                ('updateTime', models.CharField(blank=True, max_length=100)),
                ('updatedBy', models.IntegerField(default=0)),
            ],
        ),
    ]
