# Generated by Django 3.2.13 on 2022-07-29 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0008_auto_20220309_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=100)),
                ('Status', models.IntegerField(blank=True, default=0)),
                ('CreatedDate', models.CharField(blank=True, max_length=30)),
                ('CreatedTime', models.CharField(blank=True, max_length=30)),
                ('UpdatedDate', models.CharField(blank=True, max_length=30)),
                ('UpdatedTime', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='CodeType',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='item',
            name='Inventory',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='CatID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Item.category'),
            preserve_default=False,
        ),
    ]
