# Generated by Django 3.2.12 on 2022-06-14 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0002_alter_employee_salesemployeecode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampaignSetName', models.CharField(blank=True, max_length=100)),
                ('CampaignAccess', models.CharField(blank=True, max_length=250)),
                ('Description', models.CharField(blank=True, max_length=250)),
                ('LeadSource', models.CharField(blank=True, max_length=1000)),
                ('LeadPriority', models.CharField(blank=True, max_length=250)),
                ('LeadStatus', models.CharField(blank=True, max_length=250)),
                ('LeadFromDate', models.CharField(blank=True, max_length=100)),
                ('LeadToDate', models.CharField(blank=True, max_length=100)),
                ('OppType', models.CharField(blank=True, max_length=250)),
                ('OppSalePerson', models.CharField(blank=True, max_length=250)),
                ('OppStage', models.CharField(blank=True, max_length=250)),
                ('OppFromDate', models.CharField(blank=True, max_length=100)),
                ('OppToDate', models.CharField(blank=True, max_length=100)),
                ('BPType', models.CharField(blank=True, max_length=250)),
                ('BPSalePerson', models.CharField(blank=True, max_length=250)),
                ('BPCountry', models.CharField(blank=True, max_length=250)),
                ('BPState', models.CharField(blank=True, max_length=1000)),
                ('BPIndustry', models.CharField(blank=True, max_length=100)),
                ('BPFromDate', models.CharField(blank=True, max_length=100)),
                ('BPToDate', models.CharField(blank=True, max_length=100)),
                ('MemberList', models.CharField(blank=True, max_length=250)),
                ('Status', models.IntegerField(default=0)),
                ('CreateDate', models.CharField(blank=True, max_length=100)),
                ('CreateTime', models.CharField(blank=True, max_length=100)),
                ('CampaignSetOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CampaignSetOwner', to='Employee.employee', to_field='SalesEmployeeCode')),
                ('CreateBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CreateBy', to='Employee.employee', to_field='SalesEmployeeCode')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CampaignName', models.CharField(blank=True, max_length=100)),
                ('StartDate', models.CharField(blank=True, max_length=100)),
                ('EndDate', models.CharField(blank=True, max_length=100)),
                ('Type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Undefined', 'Undefined')], default='Undefined', max_length=20)),
                ('Frequency', models.CharField(choices=[('Weekly', 'Weekly'), ('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Undefined', 'Undefined')], default='Undefined', max_length=20)),
                ('Message', models.TextField(blank=True, max_length=1000)),
                ('QualityResponse', models.CharField(choices=[('High', 'High'), ('Low', 'Low'), ('Medium', 'Medium'), ('Poor', 'Poor'), ('Average', 'Average'), ('Undefined', 'Undefined')], default='Undefined', max_length=20)),
                ('Sent', models.IntegerField(default=0)),
                ('Delivered', models.IntegerField(default=0)),
                ('Opened', models.IntegerField(default=0)),
                ('Responded', models.IntegerField(default=0)),
                ('Status', models.IntegerField(default=0)),
                ('CreateDate', models.CharField(blank=True, max_length=100)),
                ('CreateTime', models.CharField(blank=True, max_length=100)),
                ('CampaignOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CampaignOwner', to='Employee.employee', to_field='SalesEmployeeCode')),
            ],
        ),
    ]
