# Generated by Django 3.2.13 on 2022-07-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignset',
            name='BPCountryCode',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='campaignset',
            name='BPStateCode',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
