# Generated by Django 3.2.13 on 2022-07-21 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0003_campaignsetmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='CampaignSetId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Campaign.campaignset'),
            preserve_default=False,
        ),
    ]
