# Generated by Django 3.2.13 on 2022-07-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0005_auto_20220725_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignset',
            name='AllBP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignset',
            name='AllLead',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campaignset',
            name='AllOpp',
            field=models.IntegerField(default=0),
        ),
    ]
