# Generated by Django 3.2.13 on 2022-07-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0006_auto_20220726_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='Status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='campaignset',
            name='Status',
            field=models.IntegerField(default=1),
        ),
    ]
