# Generated by Django 3.2.13 on 2022-07-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0007_auto_20220726_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
