# Generated by Django 3.2.13 on 2022-07-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0010_auto_20220729_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='WeekDay',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
