# Generated by Django 3.2.13 on 2022-08-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0013_campaign_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignset',
            name='BPIndustry',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
