# Generated by Django 3.2.13 on 2022-08-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Campaign', '0014_alter_campaignset_bpindustry'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='Attachments',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
