# Generated by Django 3.2.12 on 2022-06-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='SalesEmployeeCode',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
