# Generated by Django 3.2.13 on 2022-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusinessPartner', '0003_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='Size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
