# Generated by Django 3.2.13 on 2022-12-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Opportunity', '0006_opportunitytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OppItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LineNum', models.IntegerField(default=0)),
                ('OppID', models.CharField(blank=True, max_length=5)),
                ('Quantity', models.IntegerField(default=0)),
                ('UnitPrice', models.FloatField(default=0)),
                ('DiscountPercent', models.FloatField(default=0)),
                ('ItemCode', models.CharField(blank=True, max_length=20)),
                ('ItemDescription', models.CharField(blank=True, max_length=150)),
                ('TaxCode', models.CharField(blank=True, max_length=10)),
                ('U_FGITEM', models.CharField(blank=True, max_length=20)),
                ('CostingCode2', models.CharField(blank=True, max_length=20)),
                ('ProjectCode', models.CharField(blank=True, max_length=20)),
                ('FreeText', models.CharField(blank=True, max_length=500)),
                ('Tax', models.FloatField(default=0)),
                ('UomNo', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
