# Generated by Django 3.2.13 on 2022-11-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=100)),
                ('type_of_expense', models.CharField(blank=True, max_length=100)),
                ('expense_from', models.CharField(blank=True, max_length=100)),
                ('expense_to', models.CharField(blank=True, max_length=100)),
                ('totalAmount', models.IntegerField(default=0)),
                ('createDate', models.CharField(blank=True, max_length=100)),
                ('createTime', models.CharField(blank=True, max_length=100)),
                ('createdBy', models.IntegerField(default=0)),
                ('updateDate', models.CharField(blank=True, max_length=100)),
                ('updateTime', models.CharField(blank=True, max_length=100)),
                ('updatedBy', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
