# Generated by Django 3.2.13 on 2022-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_auto_20220413_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
