# Generated by Django 3.2.13 on 2022-12-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0005_alter_maps_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='shape',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='maps',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
