# Generated by Django 3.2.13 on 2022-12-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0006_auto_20221209_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='remark',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
