# Generated by Django 4.0.3 on 2022-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Host', models.CharField(blank=True, max_length=100)),
                ('Port', models.CharField(blank=True, max_length=10)),
                ('Sender', models.CharField(blank=True, max_length=200)),
                ('Password', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
