# Generated by Django 3.2.13 on 2022-11-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attachment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='Size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
