# Generated by Django 3.2.13 on 2022-07-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0008_auto_20220610_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseType',
        ),
    ]
