# Generated by Django 3.2.13 on 2022-10-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0010_leadattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadattachment',
            name='CreatedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leadattachment',
            name='UpdatedBy',
            field=models.IntegerField(default=0),
        ),
    ]
