# Generated by Django 3.2.13 on 2022-10-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0011_auto_20221006_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadattachment',
            name='Size',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
