# Generated by Django 3.2.13 on 2022-10-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lead', '0012_leadattachment_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeadId', models.IntegerField(default=0)),
                ('Title', models.CharField(blank=True, max_length=255)),
                ('Remarks', models.TextField(blank=True)),
                ('CreateDate', models.CharField(blank=True, max_length=100)),
                ('CreateTime', models.CharField(blank=True, max_length=100)),
                ('CreatedBy', models.IntegerField(default=0)),
            ],
        ),
    ]
