# Generated by Django 3.2.13 on 2022-12-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='U_OPPID',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='U_OPPRNM',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='U_QUOTID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='U_QUOTNM',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
    ]
