# Generated by Django 3.2.13 on 2022-12-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_auto_20221216_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='CancelStatus',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='NetTotal',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
